jenkins-infra/javadoc

resources/style.css, scripts/generate-javadoc-plugins.groovy
Create an index page for http://javadoc.jenkins.io/plugin/
* Show plugin name, title, version
* Link to plugin site for each plugin
* Also include plugins without Javadoc in the output with explanation why there's nothing there
Current sort order is by plugin name (`artifactId`) case-insensitively, which I think is a good choice, but perhaps not the best (sorting by title would need processing like removing "Hudson"/"Jenkins" prefixes etc. – perhaps later).
=> Add index file for plugins directory

scripts/generate-javadoc-plugins.groovy
The idea is to allow the plugin site to link to plugin Javadoc from the plugin page. For that to work, we need an easy to consume list of plugins that have Javadoc published.  Add the URL for extra flexibility even if the URL to this JSON file will need to be a configuration option.
=> [WEBSITE-386] Add index.json listing plugins with Javadoc and their URL

Dockerfile, README.adoc, scripts/generate-javadoc-components.groovy, scripts/generate-javadoc-modules.groovy, scripts/generate-javadoc-plugins.groovy, scripts/generate-javadoc.sh, src/main/groovy/Artifact.groovy, src/main/groovy/JavadocGroupBuilder.groovy, src/main/groovy/ModuleList.groovy
I needed to publish Remoting Javadocs, but after some consideration I decided to hack a more generic engine, which would support Jenkins modules and other libraries
It's built on the top of #14 
Screenshots are below:
https://issues.jenkins-ci.org/browse/INFRA-1306
@reviewbybees @rtyler @daniel-beck
=> [INFRA-1306] - Add Javadocs for Modules and other components

Dockerfile, README.adoc, scripts/generate-javadoc-plugins.groovy, scripts/generate-javadoc.sh
It should simplify the local development a bit. For me it is a prerequisite for Remoting Javadoc publishing story in [INFRA-1306](https://issues.jenkins-ci.org/browse/INFRA-1306).
https://issues.jenkins-ci.org/browse/INFRA-1305. You can try a sample image from here: https://hub.docker.com/r/onenashev/jenkins-javadoc-dev/
@reviewbybees @rtyler @christ66 @daniel-beck @abayer
=> [INFRA-1305] - Create Dockerfile for local builds and runs

Jenkinsfile
Since we typically release on Pacific daytime Sunday, this will give us a good chance to pick up the new weekly quickly.
=> Run Monday UTC morning to pick up new weekly Javadoc

scripts/generate-javadoc-components.groovy
https://github.com/jenkinsci/lib-version-number
CC @batmat
=> Add Version Number Library to the Javadoc site

scripts/generate-javadoc-components.groovy
The javadoc for the test-annotations package is related to the Jenkins test harness javadoc.  I think it should be included in the Jenkins Components javadoc page at
https://javadoc.jenkins.io/component/
=> Include test-annotations javadoc

scripts/default-to-latest.sh
Creating an explicit link to the core Javadoc index page as the root page of the site. Otherwise the component and plugin portions of this site are undiscoverable.
I am assuming #26, so not linking to modules.
Also not bothering to link to core archives, which seems a somewhat dubious feature anyway.
=> Create a root `index.html` with links to other stuff

scripts/generate-javadoc.sh
https://ci.jenkins.io/job/Infra/job/javadoc/job/master/286/consoleFull had an error
```
>> Found release 2.300
https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-core/2.300/jenkins-core-2.300-javadoc.jar:
2021-07-05 05:43:30 ERROR 404: Not Found.
mv: cannot stat 'jenkins-core-2.300-javadoc.jar': No such file or directory
java.io.FileNotFoundException: jenkins-core-2.300-javadoc.jar (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at sun.tools.jar.Main.run(Main.java:307)
at sun.tools.jar.Main.main(Main.java:1288)
>> failed to generate javadocs for 2.300
```
yet the build …
=> [WEBSITE-779] Do not proceed if download failed

scripts/generate-javadoc-components.groovy
=> Publish Javadoc for `executable-war`

scripts/generate-javadoc-components.groovy
=> Publish Javadoc for `task-reactor`

scripts/generate-javadoc.sh, src/main/groovy/JavadocGroupBuilder.groovy
See [JENKINS-68768](https://issues.jenkins.io/browse/JENKINS-68768).
Run `mvn javadoc:javadoc` against e.g. `text-finder` with Java 8.
**Note:** These are the *actual* results when running with Java 11:
No warnings are printed:
```
<INFO> --- maven-javadoc-plugin:3.4.0:javadoc (default-cli) @ text-finder ---
<INFO> Configuration changed, re-generating javadoc.
```
The following warning is printed:
```
[INFO] --- maven-javadoc-plugin:3.3.2:javadoc (default-cli) @ text-finder ---
<INFO> No previous run data found, generating javadoc.
[INFO] 
1 warning
[WARNING] Javadoc Warnings
[WARNING] javadoc: warning - Error fetching URL: https://javadoc.jenkins.io/
```
This is caused by the renaming of `package-list` to `element-list` in Java 10. I see https://javadoc.jenkins.io/element-list but …
=> [JENKINS-68768] Javadoc linking errors on Java 8

scripts/generate-javadoc.sh, src/main/groovy/JavadocGroupBuilder.groovy
See [JENKINS-68761](https://issues.jenkins.io/browse/JENKINS-68761).
Generate the Javadoc site, then attempt to search for a class in the Jenkins core or Winstone Javadocs (both compiled with Java 11).
The class is found in the search results, and clicking the link takes you to the class's Javadoc.
The class is found in the search results, but clicking on the link takes you to a nonexistent page.
This is [JDK-8215291](https://bugs.openjdk.org/browse/JDK-8215291).
Pending the merge, release, and subsequent adoption of https://github.com/openjdk/jdk11u-dev/pull/1157, work around the problem by munging the file ourselves.
Built the Javadocs locally and started a web server against the generated site. Reproduced the problem as described above, and could no longer reproduce the problem after …
=> [JENKINS-68761] javadoc.jenkins.io navigation issues with Java 11 generated javadoc

.github/CODEOWNERS
see e.g https://github.com/jenkins-infra/javadoc/pull/36 which no one noticed
(fyi @basil no one was subscribed to this repo apparently)
=> Add CODEOWNERS to request core team

.github/dependabot.yml
Since the Dockerfile depends on an older version of nginx, let's use dependabot to propose upgrades
=> Add dependabot to update Dockerfile dependency

Dockerfile, Jenkinsfile, README.adoc, src/main/groovy/JavadocGroupBuilder.groovy
- Use nginx stable (1.22.0), not 1.13.6
- Install Java 11, not Java 8
- Update examples in README
- Add sed package, needed for build process
- Rely on PATH to find sed program
- Fewer calls to apt-get
- Remove Java 8 workaround, simplify apt-get calls
=> Use Java 11

.gitignore, Jenkinsfile, scripts/generate-javadoc-plugins.groovy
Follow up to https://github.com/jenkins-infra/javadoc/pull/41, which downloads Java 11 but uses Java 8 for generation.
Additionally, I got a rid of the old mailing list and use https over http to access the UC content.
=> chore: Use jdk11 over jdk8 for gen step

Jenkinsfile
We can't have a try block without a catch phrase...
This PR build will fail, because the master branch build is broken and forks modifying Jenkinsfiles use the base repository revision.
=> fix: Remove try block

scripts/generate-javadoc-components.groovy
This component has been inlined to Jenkins core and archived.
=> Remove `executable-war`

src/main/groovy/JavadocGroupBuilder.groovy
Fixes 
* https://github.com/jenkins-infra/helpdesk/issues/3290
https://github.com/jenkins-infra/helpdesk/issues/3290 reports that javadoc builds have been failing since the release of the zdevops plugin 1.0.0.  Core javadoc is still documenting Jenkins 2.380 even though we have released 2.381 and 2.382.
When the javadoc zip file is empty or otherwise corrupt, we can safely ignore it and continue to generate the rest of the javadoc site.  No need to crash the javadoc site generation just because a damaged or flawed javadoc jar file has been published.
It is unfortunate that @IBA-mainframe-dev has not responded to the [issue](https://github.com/jenkins-infra/helpdesk/issues/3290), but the javadoc site creator script is better if it handles corrupt files without crashing.
=> Skip corrupt javadoc jar files

scripts/generate-javadoc-components.groovy
As [the `stapler` repository](https://github.com/jenkinsci/stapler) has been moved to the @jenkinsci GitHub organization, this PR updates its URL.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2466
=> chore: update `stapler` GitHub organization from `stapler` to `jenkinsci`

Jenkinsfile, scripts/generate-javadoc-components.groovy, scripts/generate-javadoc-plugins.groovy, scripts/generate-javadoc.sh, src/main/groovy/JavadocGroupBuilder.groovy
This PR is adding authentication via a basic auth for downloads done on an artifact caching proxy provider instead of the JFrog Artifactory repo.jenkins-ci.org.
It doesn't use the artifact caching proxy if it's running locally in Docker, or if it's running on trusted.ci.jenkins.io, as the corresponding credentials aren't stored there and as we're taking precaution on this sensible instance.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2752
=> Use artifact caching proxy for Javadoc generation

.gitignore, src/main/groovy/JavadocGroupBuilder.groovy
There's no `script.js` served that could be added to the header. I propose removing this line to keep the errors down to a minimum.
=> Remove 'script' from header

Jenkinsfile
The change proposed adjusts the schedule to run on Wednesday's rather than Monday's, to pick up javadoc changes of weekly core releases timely, instead of running the Monday the week after the weekly release.
=> Adjust cron schedule

Dockerfile
The nginx stable line uses an even number for the minor version digit: http://nginx.org/en/download.html
As dependabot keeps bumping it here from odd to odd number, I'm changing the version manually to stop this unwanted behavior, assuming it will shift to stable (even) versions
=> feat: bump Nginx to stable 1.24.0

Jenkinsfile
This PR adds a step to use `azcopy` to synchronize content in a new Premium File Share in parallel of `blobxfer` (for now).
When all the process will be validated, `blobxfer` and related code and script will be removed in favor of `azcopy`.
Tested via a replay of the main job on trusted.ci.jenkins.io: https://trusted.ci.jenkins.io:1443/job/javadoc/326/
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1964568638
=> chore: use `azcopy` in parallel to `blobxfer` for publication

Jenkinsfile
Reverts jenkins-infra/javadoc#70
need to check on trusted.ci for this agent not infra.ci
=> Revert "chore(javadoc): Change agent node to arm64"
